[package]
name = "tt-rs-number"
description = "Number widget for tt-rs - rational arithmetic"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tt-rs-core = { path = "../../../core/crates/tt-rs-core" }
yew = { workspace = true }
