[package]
name = "tt-rs-bird"
description = "Bird widget for tt-rs - message delivery agent"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tt-rs-core = { path = "../../../core/crates/tt-rs-core" }
yew = { workspace = true }
