[package]
name = "tt-rs-hit-test"
version = "0.1.0"
edition = "2024"

[dependencies]
tt-rs-core = { path = "../../../core/crates/tt-rs-core" }
log = "0.4"
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "DomTokenList"] }
